### ISSUE TITLE
Encrypt/Decrypt C++

### ISSUE THREAD

**Issue by 1mZ1kk4d0** [ajimae/ncrypt-js#10]
has how to make a lib for c ++? I want to make requests more secure but I'm looking for a lib to encrypt via c ++ decryptar in node.js, and when I return the answer, the token will also have encryption in the node and decrypt in c ++. I can't get anyone to help me if you can help me.

**Comment by ajimae** [comment]
Hi @GZBland this very library is specifically mean for encryption of data in a node.js environment.

For a cross platform and cross language encryption and decryption library, I would suggest you take a look at this library:

- [aes-everywhere](https://github.com/mervick/aes-everywhere)

Also, I found something on stackoverflow too
https://stackoverflow.com/questions/45631385/rsa-encryption-between-c-and-node-js

Take a look at the above links and see if they can solve your issue.

**Comment by ajimae** [comment]
I will go ahead to close this issue.
